### ISSUE TITLE
Aligning object keys differently

### ISSUE THREAD

**Issue by ShimShamSam** [adrianlee44/atom-vertical-align#10]
I'd like to see an option to align objects keys like so:

```
var foo = {
    test    : 1,
    testing : 2
}
```
Instead of

```
var foo = {
    test:    1,
    testing: 2
}
```

Also, note that there is always at least 1 space before the colons. I would think this could pretty much copy the exact logic used for "="

**Comment by QuentinRoy** [comment]
+1
(longest week ever ! :-D)

**Comment by adrianlee44** [comment]
Thanks for reminding me on this as I completely forgot about it.

**Comment by ShimShamSam** [comment]
I think this is the first package to support this option. Looking forward to the release!

**Comment by adrianlee44** [comment]
I'm still working on the README but should be releasing this very soon. The release should give the user the option to either pad left or right of the operator and if one extra whitespace should be added to the left or right.

**Comment by adrianlee44** [comment]
@ShimShamSam, @QuentinRoy

`vertical-align` has been bumped to `v0.8.0` with custom configuration support. After updated the package and restarted Atom, you can find all the options in `vertical-align` setting page.

More information can be found here, https://github.com/adrianlee44/atom-vertical-align/wiki/User-configurations

Please let me know if you run into any bugs.
